### PR TITLE
Update web pack build flow

### PR DESCRIPTION
**Pull request by anselmbradford**
Updates build to use latest webpack.

## Additions

- Babel for ES6 transpiling.

## Removals

- `gulp-uglify` replaced with webpack uglify plugin.
- `gulp-webpack` replaced with `webpack`.

## Changes

- Convert build scripts to ES6

## Testing

- `npm run build && npm test` should pass.

## Note

- This removes the un-minified versions of `capital-framework.js` and `capital-framework.css`.

### CODE REVIEW

**Comment by cfarm** [comment]
Do we want to keep the unminified CSS files as part of the released component? Is there a real use case for having this editable file? Are colleagues downloading this to use in third party software, editing it, etc?

**Comment by anselmbradford** [comment]
Note this uglify warning is coming from AtomicComponent, and is fixed there in the latest release:

```
WARNING in cf-expandables.js from UglifyJs
Dropping unused variable timer [cf-expandables.js:510,6]
Dropping unused variable isAnimating [cf-expandables.js:512,6]
```

**Comment by cfarm** [comment]
Works as advertised 👍 

@Scotchester @contolini was there a particular reason CF generated unminified CSS before? if not then this is good to merge.

**Comment by Scotchester** [comment]
Unminified output can be very helpful for debugging purposes. I would recommend keeping it.

**Comment by anselmbradford** [comment]
> Unminified output can be very helpful for debugging purposes. I would recommend keeping it.

Just comment out the minifier if this is needed, or we can add a flag to turn if off if this became a need.

**Comment by Scotchester** [comment]
What is the benefit of not outputting it all the time?

**Comment by anselmbradford** [comment]
> What is the benefit of not outputting it all the time?

There's a build complexity/performance benefit. The way it worked before was to bundle the file, rename it, save it, uglify it, rename it, save it again. With the updated webpack, uglifier is a plugin of webpack so happens at the bundling stage, so superficially the way around that I see to generate a minified and un-minified version would be to run webpack twice, which doesn't seem worth it considering how easy it is to just comment out uglifier and re-run `npm run build`. Also, I don't think this would be the correct approach to having a minified and un-minified version anyway. I think the correct way would be to have a production and development build process (set through a flag or otherwise) that could be switched between to generate production and dev assets.

**Comment by Scotchester** [comment]
That makes sense. I'd like to see us institute the two types of processes, then, because I definitely run into periodic issues where debugging CSS is a pain because we don't output unminified versions, and sourcemaps still seem to be kinda fiddly. (Typically with cfgov-refresh.)

**Comment by anselmbradford** [comment]
@Scotchester In this PR or another one?

**Comment by Scotchester** [comment]
It should probably considered out-of-scope for this PR.

**Comment by anselmbradford** [comment]
> It should probably considered out-of-scope for this PR.

I added a TODO. This also needs an update to add a webpack-config file, so that would be a good PR for that feature.

**Pull request merged**
