### PR TITLE
Bashize the travis script

### PR DESCRIPTION
**Pull request by contolini**

### CODE REVIEW

**Comment by wpears** [comment]
Break travis, self-merge, contolini you madman

**Comment by contolini** [comment]
Shhhhh everyone's away on holiday and ignoring GH notifications. Don't blow my cover.

**Comment by contolini** [comment]
$20 says @ascott1 has a folder on his desktop of Adam Scott gifs.

**Comment by ascott1** [comment]
It's called `AdamScotts`

Adam Scott the golfer

**Comment by contolini** [comment]
Scott Adams

Am I doing this right?

**Pull request merged**
