### PR TITLE
Add linting as step in Travis

### PR DESCRIPTION
**Pull request by anselmbradford**
## Additions

- Add linting as step in Travis and fail on errors.

### CODE REVIEW

**Comment by anselmbradford** [comment]
This is failing Travis but can be merged. The failure is just to demonstrate it works.

**Comment by jimmynotjim** [comment]
> but can be merged

Should we fix the failing things first? No need to hold up unrelated PRs right?

**Comment by Scotchester** [comment]
If we fix it here, we'll lose the attached evidence of Travis failing.

**Comment by jimmynotjim** [comment]
Sorry, meant fix the issues in another PR (or do the two you have open take care of all of them?)

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/capital-framework/pull/838

**Pull request merged**
