### PR TITLE
Add downloadable zip file

### PR DESCRIPTION
**Pull request by ascott1**
This adds a grunt task to zip up the build directory and some links to the files.

### CODE REVIEW

**Comment by ascott1** [comment]
selfie-0

**Comment by himedlooff** [comment]
Luckily you were wearing a shirt with a zipper...

**Comment by ascott1** [comment]
It was pretty convenient.

**Comment by himedlooff** [comment]
Hold off for a minute, grunt vendor is choking for me. I will make some tweaks to fix it before merging this PR.

**Comment by ascott1** [comment]
Perfect. Merge conflicts should be fixed and grunt vendor is working now.

**Comment by Scotchester** [comment]
Thanks, guys! This is great to see. :+1:

**Comment by himedlooff** [comment]
Looks good! Not sure why, after running `grunt`, the zip shows as modified, but we can figure that out later.

**Pull request merged**
