### PR TITLE
Keep usage.md

### PR DESCRIPTION
**Pull request by ascott1**
To be used in the documentation site.

### CODE REVIEW

**Comment by Scotchester** [comment]
I think there's something missing here. @contolini, something else has to be done to trigger a new release, right?

**Comment by Scotchester** [comment]
From the chat:
> if it’s a build process thing and doesn’t change a component just increment the root package.json

**Comment by contolini** [comment]
Yeah, Travis won't do anything unless it notices a manifest has been bumped (either a component's or the root's). So change [3.1.2 to 3.1.3](https://github.com/cfpb/capital-framework/blob/canary/package.json#L3).

**Comment by ascott1** [comment]
:+1:

**Comment by Scotchester** [comment]
:+1: Here goes nothin'!

**Pull request merged**
