### PR TITLE
Moved atoms, molecules, organisms into src folder

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
After some discussion in the Dada team, this commit makes the way we
organize code consistent across all the cf components.

## Review
- @jimmynotjim

### CODE REVIEW

**Comment by mistergone** [comment]
Hooray, this answers my concerns about directory structure in https://github.com/cfpb/capital-framework/pull/386!

**Comment by jimmynotjim** [comment]
👍

**Comment by jimmynotjim** [comment]
Before we merge, should we add this to the changelog just in case it comes up in the future?

**Comment by KimberlyMunoz** [comment]
We haven't bumped the version since we've started atomic designing, so it should be fine, ~but~ there's a lot of new things we should changelog. I'll get that in a new PR.

**Comment by jimmynotjim** [comment]
All of the atomic work will be bumped as one when it's released, but I've been trying to keep track of whats changed just so we can create a decent document when that time comes.

**Pull request merged**
