### PR TITLE
Restructure the entire thing

### LINKED ISSUE #148: Project Organization and Workflow
Should this repo be updated to match the organization and workflow created by the generator? If I were to come to this repo trying to understand how a CF project works, I'd be really confused because my generated project wouldn't match up what I'm seeing here.

### PR DESCRIPTION
**Pull request by contolini**
This PR updates this repo to use our standardized best practices. Fixes #148 and #143.

## Changes
- `assets/` and `build/` dirs changes to `static/` and `dist/`. `src/` was not used because `capital-framework.less` is in that directory.
- Gruntfile overhaul.
- Location of archive moved from `assets/cf.zip` to `releases/capital-framework-x.x.x.zip` *and* `releases/capital-framework-latest.zip`
- Lots of general tidying.

## Review

- @Scotchester 
- @ascott1 
- @himedlooff

### CODE REVIEW

**Comment by ascott1** [comment]
screen shot 2015-06-05 at 6 10 55 am
 :smile:

**Comment by ascott1** [comment]
I pulled this down locally and everything looks a-ok. @Scotchester or @himedlooff once you give the thumbs I up, let's merge this :poodle:

**Comment by Scotchester** [comment]
Link to the archive needs to be updated on the Getting Started page, as well.

**Comment by ascott1** [comment]
I have a pull request immediately following this one. I'll make that change in mine. PRESSING THE BUTTON

**Comment by contolini** [comment]
BTW, the contents of the archive now look like this:

```
dist/
├── capital-framework.css
├── capital-framework.ie.css
├── capital-framework.ie.min.css
├── capital-framework.js
├── capital-framework.min.css
├── capital-framework.min.js
└── demo-app
    ├── CHANGELOG.md
    ├── CONTRIBUTING.md
    ├── Gruntfile.js
    ├── LICENSE
    ├── README.md
    ├── TERMS.md
    ├── bower.json
    ├── dist
    │   ├── index.html
    │   └── static
    │       ├── css
    │       │   ├── main.css
    │       │   ├── main.ie.css
    │       │   ├── main.ie.min.css
    │       │   └── main.min.css
    │       ├── fonts
    │       │   ├── cf-icons.eot
    │       │   ├── cf-icons.svg
    │       │   ├── cf-icons.ttf
    │       │   └── cf-icons.woff
    │       ├── js
    │       │   ├── main.js
    │       │   ├── main.min.js
    │       │   └── main.min.js.map
    │       └── vendor
    │           └── box-sizing-polyfill
    │               └── boxsizing.htc
    ├── package.json
    ├── screenshot.png
    └── src
        ├── index.html
        └── static
            ├── css
            │   ├── brand-palette.less
            │   ├── cf-enhancements.less
            │   ├── cf-theme-overrides.less
            │   ├── licensed-fonts.css
            │   └── main.less
            └── js
                └── app.js
```

Good? Bad?

**Comment by Scotchester** [comment]
In the `demo-app` folder, I'd get rid of everything but the contents of `demo-app/dist/`. Like this:

```
capital-framework-latest.zip
├── capital-framework.css
├── capital-framework.ie.css
├── capital-framework.ie.min.css
├── capital-framework.js
├── capital-framework.min.css
├── capital-framework.min.js
└── demo-app
   ├── index.html
   └── static
       ├── css
       │   ├── main.css
       │   ├── main.ie.css
       │   ├── main.ie.min.css
       │   └── main.min.css
       ├── fonts
       │   ├── cf-icons.eot
       │   ├── cf-icons.svg
       │   ├── cf-icons.ttf
       │   └── cf-icons.woff
       ├── js
       │   ├── main.js
       │   ├── main.min.js
       │   └── main.min.js.map
       └── vendor
           └── box-sizing-polyfill
               └── boxsizing.htc
```

**Comment by contolini** [comment]
Roger wilco.

**Comment by himedlooff** [comment]
I don't think the CSS needed for the capital framework website should be compiled into `capital-framework.css` in the zip file.

**Comment by Scotchester** [comment]
@himedlooff See also #176 :)

**Comment by contolini** [comment]
@himedlooff `capital-framework.css` is the compiled CSS that people can download if they don't want to use Less or Bower or anything. It's not specific to the CF website. I simply point the CF website to that file, rather than generate a unique `main.css`.

#176 should solve this confusion.

**Comment by himedlooff** [comment]
But it is specific to the CF website. If you look at the bottom of the file you will see CF website specific styles in there. There should be a separate LESS task in the Gruntfile to compile two stylesheets, one for the site and one for people to download and use.

Apologies if I'm missing something obvious here.

**Comment by contolini** [comment]
Ah, you're correct! I'll fix this in the PR that's currently open.

**Pull request merged**
