### PR TITLE
Release: buncha bug fixes and small updates in core and layout

### PR DESCRIPTION
**Pull request by Scotchester**
**Reveiw:**
- @contolini
- @jimmynotjim

### CODE REVIEW

**Comment by contolini** [comment]
@Scotchester Can you add [`sudo: false`](https://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure) to the .travis.yml?

**Comment by Scotchester** [comment]
@contolini According to [the way in which their defaults for that option were set](https://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure), we should be using the containerized infrastructure.

What I'm not sure about is how to confirm whether or not it's doing that. Do you know how?

**Comment by Scotchester** [comment]
Also, some of our builds have this message:

> This job ran on our new platform for Precise builds. Please read [our blog post for more information](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future).

The linked post mentions containerized builds at the bottom, but I don't really understand it.

**Comment by contolini** [comment]
Never mind! Turns out we are using the new infrastructure. I guess it's just not a whole lot faster.

**Comment by contolini** [comment]
:+1: Looks good. We'll know after this is merged if I missed any steps in the `Release management` section of the docs.

**Comment by Scotchester** [comment]
We decided to add it anyway, to ensure our bases are covered. Doesn't seem to be any potential downside.

**Pull request merged**
