### PR TITLE
Updated pages site to 3.6.0

### PR DESCRIPTION
**Pull request by jimmynotjim**
Re-generated pages site to use latest release of Capital Framework

## Changes

- Updated CF to 3.6.0 release

## Testing

- Run the site and check that it still works and that cf-grid documentation is up to date.

## Review

- @KimberlyMunoz 
- @Scotchester 
- @contolini 

## Screenshots

__Old__

screen shot 2016-08-10 at 11 45 07 am

__New__

screen shot 2016-08-10 at 11 45 51 am

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Do we need to update the changelog in the gh-pages branch? It hasn't been updated since v2.0.0

**Comment by contolini** [comment]
@jimmynotjim meh. I vote to delete it.

**Comment by contolini** [comment]
👍

**Comment by contolini** [comment]
cf-forms still has the ugly double heading but that doesn't concern this PR.

screen shot 2016-08-10 at 1 47 52 pm

**Comment by Scotchester** [comment]
:+1:

**Pull request merged**
