### PR TITLE
Update hero instructions

### PR DESCRIPTION
**Pull request by jimmynotjim**
Updating hero instructions to match Generator instructions
 
## Additions
 
None
 
## Removals
 
None

## Changes
 
- added instructions from Generator README
 
## Testing
 
- None
 
## Review
 
- @Scotchester 
- @contolini 
- @ascott1 
 
## Preview
 
screen shot 2015-03-27 at 5 29 24 pm

## Notes
 
- Fixes [generator-cf #31](https://github.com/cfpb/generator-cf/issues/31)

### CODE REVIEW

**Comment by ascott1** [comment]
Looks good. I might nix the `open ./dist/index.html` bit, but I can be convinced otherwise.

**Comment by jimmynotjim** [comment]
@ascott1 I included it in the generator README because I feel like without it you're just left wondering "now what" when you're new to the project. Taking a look at the index file allows you to sort of "kick the tires" and get a feel for how things work, and from there you can get working. 

I also wonder if we shouldn't explain that the index file is copied from `src/` because that could suck if you're markup work in `dist/`was overwritten upon building.

Overall, I've tried to apply viewpoint of a new user to all the changes I've submitted this week.

**Comment by ascott1** [comment]
Makes sense. To me "quick start" implies that you're comfortable digging in a bit, but we should be as explicit as possible on the "getting started" page.

**Comment by jimmynotjim** [comment]
Ah, I forgot about the "getting started" page. Maybe we just need to call that out a bit more? Right now it's a bit lost with the other two lines on dependencies and compiled source. 

If we were to do that I think I could remove 
```
$ grunt
$ open ./dist/index.html
```

leaving
```
$ npm install -g yo generator-cf
$ mkdir my-new-project && cd $_
$ yo cf
```

in the hero.

**Comment by ascott1** [comment]
:+1: I think that's good and brief for the hero and we can add those explicit instructions to the getting started page. 

I agree that we should probably call that page out a bit more. It's a teeny tiny link.

**Comment by jimmynotjim** [comment]
All updated. If this is good I'll squash it down for merging.

**Comment by Scotchester** [comment]
:+1:

**Comment by jimmynotjim** [comment]
Squashed and ready

**Pull request merged**
