### PR TITLE
Fix default super button font size

### PR DESCRIPTION
**Pull request by Scotchester**
The default font size for super buttons was out-of-step with [the standard](http://cfpb.github.io/design-manual/page-components/buttons.html#large-primary-button).

## Changes

- Changes the value of `@btn__super-font-size` to 18px.

## Review

- @jimmynotjim 
- @ajbush
- @caheberer

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by ajbush** [comment]
👍

**Comment by Scotchester** [comment]
Thanks, Atom spellcheck 😁

**Comment by caheberer** [comment]
👍

**Comment by Scotchester** [comment]
Interesting. Seems like Travis chokes on commits created by doing conflict resolution via the GitHub UI, which is what that last merge commit ☝️ was. I've restarted the build twice and it keeps telling me

> fatal: Couldn't find remote ref refs/pull/478/merge
> Unexpected end of command stream
> The command "eval git fetch origin +refs/pull/478/merge: " failed.

**Comment by jimmynotjim** [comment]
🎵 They see me rebasing, they hating, caauuse I got no Trav-is problems 🎵

**Pull request merged**
