### PR TITLE
Adjust heading class styles

### LINKED ISSUE #783: Prevent h5 and h6 styles from leaking into .h1-4 classes
When a `.h1`, `.h2`, `.h3`, or `.h4` class is added to `<h5>` or `<h6>` they don’t look correct because they get the letter-spacing, text-shadow, and text-transform of h5 or h6.

## Current behavior

- `<h5>` or `<h6>` elements with a `.h1`, `.h2`, `.h3`, or `.h4` class don’t 100% match the look of the corresponding heading element.

## Expected behavior

- `<h5>` or `<h6>` elements with a `.h1`, `.h2`, `.h3`, or `.h4` class should 100% match the look of the corresponding heading element.

## Steps to replicate behavior

1. Add `.h1`, `.h2`, `.h3`, or `.h4` class to an `<h5>` or `<h6>` element.

## Screenshots

__Current__
image

__Expected__
image

### PR DESCRIPTION
**Pull request by dcmouyard**
Prevent `<h5>` and `<h6>` styles from leaking into .h1, .h2, .h3, and .h4 classes. Fixes #783 

## Additions

- Add letter-spacing and text-transform overrides for .h1, .h2, .h3, and .h4 classes.

## Testing

1. Pull branch and follow https://github.com/cfpb/capital-framework/blob/canary/CONTRIBUTING.md#testing-components-locally

### Before
image

### After
image

## Checklist

- [ ] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [ ] Code follows the standards laid out in the [development playbook](https://github.com/cfpb/development)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Internet Explorer 8, 9, 10, and 11
- [ ] Edge
- [ ] iOS Safari
- [ ] Chrome for Android

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by cfarm** [comment]
Dan, this is very exciting!!! Yeah open source!

Can you share more about what happened with the before state? Example code for context? I don't think our uppercase / text-shadow css should be affecting headings other than h5 and h6 like that, just want to make sure I understand the problem you're solving here!

**Comment by cfarm** [comment]
OK I'm reading the bug now which has more info! My bad :)

**Comment by cfarm** [comment]
We JUST recently removed that text-shadow from the h5/h6 so if that affects the code here you can take that into account.

**Comment by jimmynotjim** [comment]
@dcmouyard this looks good, tested it on a branch on origin and Travis passes fine so I think that failure is something we're going to have to deal with on our end. Before we merge it, can you add an entry to the changelog. Take a second to [check out an example from this merged PR](https://github.com/cfpb/capital-framework/pull/778/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR15) to understand the format that the release bot can ingest. You're change would be the same component and `[PATCH]` flag with the obvious change to the description.

**Comment by Scotchester** [comment]
Travis failure is due to our script not supporting PRs from forks, unfortunately. Merging!

**Pull request merged**
