### PR TITLE
Updates dependencies

### PR DESCRIPTION
**Pull request by anselmbradford**
## Changes

- Updates `gulp-rename`.
- Updates `silent-npm-registry-client`.

## Testing

1. `npm install`
1. `gulp test` should pass.

## Notes

- I'm not totally certain whether this change is covered by the tests or whether we need to make a release to be sure nothing is broken.

### CODE REVIEW

**Comment by Scotchester** [comment]
I don't know if it's related to this PR or was already happening, but when I run `gulp test`, I get a bunch of `jest-haste-map: @providesModule naming collision` warnings.

**Comment by Scotchester** [comment]
Yeah, but isn't it supposed to be there?

**Comment by anselmbradford** [comment]
@Scotchester err right. Try it now.

**Comment by jimmynotjim** [comment]
> I'm not totally certain whether this change is covered by the tests or whether we need to make a release to be sure nothing is broken.

I'm not sure of the answer here, but I'd like to do a release just to be sure, I think about 80% of the release stuff is unit tested.

**Pull request merged**
