### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by KimberlyMunoz**
As I was creating the sandbox for the Capital Framework sandbox, I noticed a few huge documentation markup issues. This fixes those issues.

## Changes

-  Fixes markup in the documentation in cf-typography and cf-forms

## Testing

- tbh, I don't know how to locally generate the documentation. I would love if someone point me to the documentation on that.

## Screenshots

This is what is fixed.

image

image

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by Scotchester** [comment]
👍

**Comment by Scotchester** [comment]
The gh-pages branch will need its own rebuild and PR to make the changes live.

**Comment by KimberlyMunoz** [comment]
Are the steps for that documented anywhere or should I just go digging into old PRs?

**Comment by Scotchester** [comment]
There are some basic setup steps in the [gh-pages README](https://github.com/cfpb/capital-framework/tree/gh-pages). After that, `gulp watch` is running, but I think you'll have to manually kick off a full re-build with `gulp build`.

Looking at the scripts, it also looks like the component updates will need to be published in order for the `gulp usage` script to do its thing correctly (for it to have the latest versions of each component's `usage.md` file).

We might consider changing how it pulls in those `usage.md` files so they don't have to be released yet.

/cc @ascott1 @contolini

**Comment by KimberlyMunoz** [comment]
The changes can wait for another release.

It's way more important to have these steps documented in this `CONTRIBUTING.md` once we figure out the process, rather than having some of the documentation on another branch and guessing on the best way to contribute. External folks wouldn't even know that editing the `usage.md` files are how you edit the documentation at this point.

**Comment by contolini** [comment]
I'm not 100% sure how to update the documentation but I think @Scotchester's steps are correct. @ascott1 would know more. I'll file an issue to have us document it. After it's documented we should automate it.

**Comment by KimberlyMunoz** [comment]
:clap: 

I'll take on a best guess with @cfarm, but we can run through them and make sure they're correct in the next release or wait until Adam gets back.

**Pull request merged**
