### PR TITLE
Gh-pages docs: fix font path for cf-icons

### PR DESCRIPTION
**Pull request by cfarm**
Fixes gulp config to put the fonts folder where Capital Framework cf-icons component and documentation expects them to be.

## Changes

- updated gulp/config.js with the correct file path
- re-compiled with `npm run build`

## Testing

- check out branch
- `npm start`
- Confirm icons work on [cf-notification](http://localhost:3000/components/cf-notification/) and [cf-icons](http://localhost:3000/components/cf-icons/) docs - they shouldn't 404 anymore.

## Screenshots
screen shot 2017-09-06 at 5 30 54 pm
screen shot 2017-09-06 at 5 30 45 pm

## Notes

-

## Todos

-

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### Browsers

- [ ] Chrome
- [ ] Safari
- [ ] FF
- [ ] IE10
- [ ] IE9
- [ ] IE8
- [ ] Opera
- [ ] iOS
- [ ] Android
- [ ] Blackberry Bold

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by jimmynotjim** [comment]
Looks like @anselmbradford changed the base branch from Canary to gh-pages. Unfortunately gh-pages also has to be the root when the branch was created. Sorry to make you redo it @cfarm, but maybe this is another reason to move the docs into a directory in canary instead of it's own branch.

**Comment by anselmbradford** [comment]
> docs into a directory in canary instead of it's own branch.

💯 

@jimmynotjim An idea is that the docs are a published module inside CF, which the DM can then import and the gh-pages branch can also import. Do you think this could work in theory?

**Comment by jimmynotjim** [comment]
The individual docs are already in their own Modules within CF and are installed into the docs site via NPM. The docs site just converts them and adds all the other docs specific pages and assets. Before a docs site had to be it's own branch, but now GH allows you to publish from a single directory.

**Comment by cfarm** [comment]
doh

**Comment by cfarm** [comment]
ok, this IS branched off gh-pages. the file changes are all the compiled markdown and css. not sure why it's showing those diffs for the usage files- those should have come in #565 🤷‍♀️

**Comment by cfarm** [comment]
for the record, if anyone tries to PR from canary to gh-pages, it's a LOT more file changes than the 19 in this PR :)

**Pull request merged**
