### PR TITLE
Add new cf-tables component

### LINKED ISSUE #264: Add cf-tables to Capital Framework
Existing singleton repo: https://github.com/cfpb/cf-tables

Test out (and document!) the process of adding a new component to Voltrazord.

Consult with @contolini, if necessary.

### PR DESCRIPTION
**Pull request by contolini**
New component from @mistergone!

## Additions

- New cf-tables component

## Review

- @Scotchester 
- @cfpb/front-end-team-admin 

## Notes

- I set its starting version to 1.0.0.
- This is a new component so it won't need to be incremented during the next release (so I didn't include a version signifier).
- Fixes #264

### CODE REVIEW

**Comment by contolini** [comment]
Oop we forgot a screenshot. @mistergone can you take a screenshot of the component when you have a second? Name it `screenshot.png` and stick it in the [cf-tables directory](https://github.com/cfpb/capital-framework/tree/cf-tables/src/cf-tables) on the cf-tables branch. No need to fork this repo, just push directly to the cf-tables branch and it will update this PR.

**Comment by contolini** [comment]
@mistergone lmk if you need help with this.

**Comment by mistergone** [comment]
Sorry, I dropped the ball here - screenshot added!

**Comment by Scotchester** [comment]
:+1:

**Comment by contolini** [comment]
:shipit:

**Pull request merged**
